name: Verany-HubSystem
author: Nico Kempe, Maximilian Wiegmann
version: 1.1
api-version: 1.16
main: net.verany.hubsystem.HubSystem

commands:
  setup:
    aliases: [set]
  togglerank:
    aliases: [trank]
  build:
    aliases: [buildserver]
  event:

loadBefore:
  - MC-Core-Executor

depend:
  - MC-Core-Executor